from src.net.client.character.items.item import Item


class Equip(Item):
    """
    Inherits Item, see item.py for standard attributes
    """
    def __init__(
            self,
            serial_number=0,
            title="",
            equipped_date=0,
            prev_bonux_xp_rate=0,
            tuc=0,
            istr=0,
            idex=0,
            iint=0,
            iluk=0,
            imax_hp=0,
            imax_mp=0,
            ipad=0,
            imad=0,
            ipdd=0,
            imdd=0,
            iacc=0,
            ieva=0,
            icraft=0,
            ispeed=0,
            ijump=0,
            attribute=0,
            level_up_type=0,
            level=0,
            exp=0,
            durability=0,
            iuc=0,
            ipvp_damage=0,
            ireduce_req=0,
            special_attrib=0,
            durability_max=0,
            iinc_req=0,
            growth_enchant=0,
            ps_enchant=0,
            bdr=0,
            imdr=0,
            boss_reward=0,
            superior_equip=0,
            dam_r=0,
            stat_r=0,
            cuttable=0,
            ex_grade_option=0,
            hyper_upgrade=0,
            item_state=0,
            chuc=0,
            soul_option_id=0,
            soul_socket_id=0,
            soul_option=0,
            rstr=0,
            rdex=0,
            rint=0,
            rluk=0,
            rlevel=0,
            rjob=0,
            rpop=0,
            special_grade=0,
            fixed_potential=False,
            no_potential=False,
            trade_block=False,
    ):
        super().__init__()
        self._serial_number = serial_number
        self._title = title
        self._equipped_date = equipped_date
        self._prev_bonux_xp_rate = prev_bonux_xp_rate
        self._tuc = tuc
        self._istr = istr
        self._idex = idex
        self._iint = iint
        self._iluk = iluk
        self._imax_hp = imax_hp
        self._imax_mp = imax_mp
        self._ipad = ipad
        self._imad = imad
        self._ipdd = ipdd
        self._imdd = imdd
        self._iacc = iacc
        self._ieva = ieva
        self._icraft = icraft
        self._ispeed = ispeed
        self._ijump = ijump
        self._attribute = attribute
        self._level_up_type = level_up_type
        self._level = level
        self._exp = exp
        self._durability = durability
        self._iuc = iuc
        self._ipvp_damage = ipvp_damage
        self._ireduce_req = ireduce_req
        self._special_attrib = special_attrib
        self._durability_max = durability_max
        self._iinc_req = iinc_req
        self._growth_enchant = growth_enchant
        self._bdr = bdr
        self._imdr = imdr
        self._boss_reward = boss_reward
        self._superior_equip = superior_equip
        self._dam_r = dam_r
        self._stat_r = stat_r
        self._cuttable = cuttable
        self._ex_grade_option = ex_grade_option
        self._hyper_upgrade = hyper_upgrade
        self._item_state = item_state
        self._chuc = chuc
        self._soul_option_id = soul_option_id
        self._soul_socket_id = soul_socket_id
        self._soul_option = soul_option
        self._rstr = rstr
        self._rdex = rdex
        self._rint = rint
        self._rluk = rluk
        self._rlevel = rlevel
        self._rjob = rjob
        self._rpop = rpop
        self._special_grade = special_grade
        self._fixed_potential = fixed_potential
        self._no_potential = no_potential
        self._trade_block = trade_block
