class CharacterStat:
    def __init__(
            self,
            chr_stat_id=0,
            chr_id=0,
            world_id_for_log=0,
            name="",
            gender=0,
            skin=0,
            face=0,
            hair=0,
            mix_base_hair_color=0,
            mix_add_hair_color=0,
            mix_hair_base_prob=0,
            level=0,
            job=0,
            strength=4,
            dex=4,
            inte=4,
            luk=4,
            hp=50,
            max_hp=50,
            mp=50,
            max_mp=50,
            ap=0,
            sp=0,
            exp=0,
            pop=0,  # fame
            money=0,
            wp=0,
            pos_map=0,
            portal=0,
            sub_job=0,
            def_face_acc=0,
            fatigue=0,
            last_fatigue_update_time=0,
            charisma_exp=0,
            insight_exp=0,
            will_exp=0,
            craft_exp=0,
            sense_exp=0,
            charm_exp=0,
            pvp_exp=0,
            pvp_grade=0,
            pvp_point=0,
            pvp_mode_level=0,
            pvp_mode_type=0,
            event_point=0,
            alba_activity_id=0,
            alba_start_time=0,
            alba_duration=0,
            alba_special_reward=0,
            burning=False,
            character_card=None,
            gach_exp=0,
            honor_exp=0,
            wing_item=0
    ):
        self._chr_stat_id = chr_stat_id
        self._chr_id = chr_id
        self._world_id_for_log = world_id_for_log
        self._name = name
        self._gender = gender
        self._skin = skin
        self._face = face
        self._hair = hair
        self._mix_base_hair_color = mix_base_hair_color
        self._mix_add_hair_color = mix_add_hair_color
        self._mix_hair_base_prob = mix_hair_base_prob
        self._level = level
        self._job = job
        self._strength = strength
        self._dex = dex
        self._inte = inte
        self._luk = luk
        self._hp = hp
        self._max_hp = max_hp
        self._mp = mp
        self._max_mp = max_mp
        self._ap = ap
        self._sp = sp
        self._exp = exp
        self._pop = pop  # fame
        self._money = money
        self._wp = wp
        self._pos_map = pos_map
        self._portal = portal
        self._sub_job = sub_job
        self._def_face_acc = def_face_acc
        self._fatigue = fatigue
        self._last_fatigue_update_time = last_fatigue_update_time
        self._charisma_exp = charisma_exp
        self._insight_exp = insight_exp
        self._will_exp = will_exp
        self._craft_exp = craft_exp
        self._sense_exp = sense_exp
        self._charm_exp = charm_exp

        self._pvp_exp = pvp_exp
        self._pvp_grade = pvp_grade
        self._pvp_point = pvp_point
        self._pvp_mode_level = pvp_mode_level
        self._pvp_mode_type = pvp_mode_type
        self._event_point = event_point
        self._alba_activity_id = alba_activity_id
        self._alba_start_time = alba_start_time
        self._alba_duration = alba_duration
        self._alba_special_reward = alba_special_reward
        self._burning = burning
        self._character_card = character_card
        self._gach_exp = gach_exp
        self._honor_exp = honor_exp
        self._wing_item = wing_item
