from enum import Enum


class OutPacket(Enum):
    """
    LOGIN OPCODES
    OutHeaders
    """
    # Can be found in CLogin::OnPacket
    CHECK_PASSWORD_RESULT = 0
    WORLD_INFORMATION = 1
    LATEST_CONNECTED_WORLD = 2
    RECOMMENDED_WORLD_MESSAGE = 3
    SET_CLIENT_KEY = 4
    SET_PHYSICAL_WORLD_ID = 5
    SELECT_WORLD_RESULT = 6
    SELECT_CHARACTER_RESULT = 7
    ACCOUNT_INFO_RESULT = 8
    CREATE_MAPLE_ACCOUNT_RESULT = 9
    CHECK_DUPLICATED_ID_RESULT = 10
    CREATE_NEW_CHARACTER_RESULT = 11
    DELETE_CHARACTER_RESULT = 12
    RESERVED_DELETE_CHARACTER_RESULT = 13
    RESERVED_DELETE_CHARACTER_CANCEL_RESULT = 14
    RENAME_CHARACTER_RESULT = 15
    SET_CHARACTER_ID = 16
    MIGRATE_COMMAND = 17
    ALIVE_REQ = 18
    PING_CHECK_RESULT = 19
    AUTHEN_CODE_CHANGED = 20
    AUTHEN_MESSAGE = 21
    SECURITY_PACKET = 22
    PRIVATE_SERVER_PACKET = 23
    CHANGE_SPW_RESULT = 24
    ALBA_RESULT = 29
    SET_AUTO_SELECTED_WORLD = 32
    WORLD_INFO_FOR_SHINING_RESULT = 33
    CLIENT_START = 36
    SERVER_STATUS = 38
    INIT_OPCODE_ENCRYPTION = 40
    AUTH_SERVER = 47
